In [1]:
import streamlit as st
import pandas as pd
import re

In [5]:
df_zjgsu = pd.read_excel('zjgsu_journal_rank_en.xlsx', index_col=0)
df_zjgsu

   area                                            title  rank type
id
1    综合                                          SCIENCE    顶级   综合
2    综合                                           NATURE    顶级   综合
3    综合                                             CELL    顶级   综合
4    综合                                           LANCET    顶级   综合
1    综合                                      《SCIENCE》子刊  A+++   综合
..  ...                                              ...   ...  ...
66   数学               SIAM JOURNAL ON NUMERICAL ANALYSIS    A+  理工类
67   数学                            MATHEMATISCHE ANNALEN    A+  理工类
68   数学     MEMOIRS OF THE AMERICAN MATHEMATICAL SOCIETY    A+  理工类
69   数学     JOURNAL DE MATHEMATIQUES PURES ET APPLIQUEES    A+  理工类
70   数学  JOURNAL FUR DIE REINE UND ANGEWANDTE MATHEMATIK    A+  理工类

[866 rows x 4 columns]